### Ports
server:
  port: 7634

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
    endpoint:
      health:
        show-details: always

spring:
  ### Profiles
  profiles:
    active: textlogs

  ### Turn off Spring Boot banner
  main:
    banner-mode: off

search: "365DaysOfCode"
bearerToken: AAAAAAAAAAAAAAAAAAAAAN5keQEAAAAASPtbLI5Wxerefb7hYlCrS7qSLJk%3DxZW1103iI7ffGfVbOyif49yUksb0pi4WpxpPFuXVSU04XSAqGl
  
oauth:
  consumerKey: ${CONSUMERKEY}
  consumerSecret: ${CONSUMERSECRET}
  accessToken: ${ACCESSTOKEN}
  accessTokenSecret: ${ACCESSTOKENSECRET}
  grantType: client_credentials